module.exports = {
  Ping: require('./ping'),
  Help: require('./help'),
  Save: require('./save'),
  List: require('./list'),
  TMI: require('./testmyitalian'),
  TME: require('./testmyenglish'),
  TR: require('./testrandom'),
  TRI: require('./testrandomitalian'),
  TRE: require('./testrandomenglish'),
  Search: require('./search'),
  Random: require('./random'),
  itl: require('./getitl'),
  eng: require('./geteng'),
  Download: require('./downloadlist'),
  Delete: require('./del'),
};
